### ISSUE TITLE
Bug in __init__ upon attempting to create a new config directory.

### ISSUE THREAD

**Issue by GTG3000** [medeor413/Red_Star#163]
Attaching error:
```
PS C:\Users\***\Desktop\Discord Bots\Red Star> py .\red_star.py -v
>>
2018-09-27 18:05:18 - WARNING - root # Specified config directory C:\Users\***\.red_star does not exist! Creating now...
Traceback (most recent call last):
  File ".\red_star.py", line 4, in <module>
    main()
  File "C:\Users\***\Desktop\Discord Bots\Red Star\red_star\__init__.py", line 43, in main
    config_folder = args.config / "config"
AttributeError: 'Namespace' object has no attribute 'config'
```

**Comment by medeor413** [comment]
Fixed in 2.0.1.
